DROP DATABASE IF EXISTS produitsdb;
CREATE DATABASE produitsdb;
USE produitsdb;


CREATE TABLE PRODUIT (
	CODE VARCHAR(2) NOT NULL,
	DESCRIPTION VARCHAR(100) NULL,
	PRIX DOUBLE NOT NULL,
	PRIMARY KEY (CODE)
);

INSERT INTO PRODUIT(CODE, DESCRIPTION, PRIX) VALUES 
("P1", "Produit 1", 1250),
("P2", "Produit 2", 2300.50),
("P3", "Produit 3", 5000.75);
